package service.custom.impl;

import dto.EmployeeDTO;
import jakarta.inject.Inject;
import Entity.User;
import Entity.UserCredential;
import repository.custom.EmployeeRepository; // Assuming this now handles User entities
import service.custom.EmployeeService;
import util.PasswordUtil;

import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

public class EmployeeServiceImpl implements EmployeeService {

    private static final Logger logger = Logger.getLogger(EmployeeServiceImpl.class.getName());

    @Inject
    EmployeeRepository repositoryType;

    @Override
    public boolean addEmployee(EmployeeDTO dto) {
        User user = convertToEntity(dto, new User());
        try {
            // if user with same id exists, perform update instead of create
            if (user.getUserId() != null && !user.getUserId().isEmpty()) {
                try {
                    User existing = repositoryType.getById(user.getUserId());
                    if (existing != null) {
                        return repositoryType.update(user);
                    }
                } catch (Exception ignored) {
                    // if getById fails, proceed to create
                }
            }
            return repositoryType.create(user);
        } catch (Exception e) {
            logger.log(Level.SEVERE, "Failed to add employee", e);
            return false;
        }
    }

    @Override
    public boolean updateEmployee(EmployeeDTO dto) throws SQLException {
        User user = repositoryType.getById(dto.getEmployeeId());

        user.setFirstName(dto.getFirstName());
        user.setLastName(dto.getLastName());
        user.setContactNo(dto.getContactNo());
        user.setSalary(dto.getSalary());
        user.setUserRole("Admin".equalsIgnoreCase(dto.getUserRole()) ? 1 : 2);
        if (dto.getHireDate() != null) {
            user.setHireDate(dto.getHireDate());
        }
        user.setActive(dto.isActive());

        if (dto.getPassword() != null && !dto.getPassword().trim().isEmpty()) {
            if (user.getUserCredential() == null) {
                user.setUserCredential(new UserCredential());
            }
            user.getUserCredential().setPassword(PasswordUtil.encrypt(dto.getPassword()));
        }
        user.getUserCredential().setEmail(dto.getEmail());
        return repositoryType.update(user);
    }

    @Override
    public List<EmployeeDTO> getAllEmployees() throws SQLException {
        List<User> users = repositoryType.getAll();
        List<EmployeeDTO> employeeDTOs = new ArrayList<>();

        if (users != null) {
            for (User user : users) {
                employeeDTOs.add(convertToDTO(user));
            }
        }
        return employeeDTOs;
    }

    @Override
    public EmployeeDTO searchEmployee(String id) throws SQLException {
        User user = repositoryType.getById(id);
        if (user != null) {
            return convertToDTO(user);
        }
        return null;
    }

    @Override
    public boolean deleteEmployee(String id) {
        return repositoryType.deleteById(id);
    }

    @Override
    public String getEmployeeId() {
        Long rowCount = repositoryType.getRowCount();
        if (rowCount == null || rowCount == 0) {
            return "EMP-0001";
        } else {
            int newIdNum = rowCount.intValue()+1 ;
            return String.format("EMP-%04d", newIdNum);
        }
    }


    private User convertToEntity(EmployeeDTO dto, User user) {
        // set ID if present (important for create when ID isn't generated by DB)
        if (dto.getEmployeeId() != null && !dto.getEmployeeId().trim().isEmpty()) {
            user.setUserId(dto.getEmployeeId());
        }

        user.setFirstName(dto.getFirstName());
        user.setLastName(dto.getLastName());
        user.setContactNo(dto.getContactNo());
        user.setSalary(dto.getSalary());

        // Convert Role String to Integer (Assuming Admin = 1, Staff = 2)
        user.setUserRole("Admin".equalsIgnoreCase(dto.getUserRole()) ? 1 : 2);

        // Convert LocalDate to java.util.Date
        if (dto.getHireDate() != null) {
            user.setHireDate(dto.getHireDate());
        }

        user.setActive(dto.isActive());

        // Handle the One-to-One Credentials Mapping
        UserCredential credential = user.getUserCredential();
        if (credential == null) {
            credential = new UserCredential();
        }
        credential.setEmail(dto.getEmail());
        credential.setPassword(dto.getPassword());

        // Establish bidirectional relationship
        credential.setUser(user);
        user.setUserCredential(credential);

        return user;
    }

    private EmployeeDTO convertToDTO(User user) {
        EmployeeDTO dto = new EmployeeDTO();

        dto.setEmployeeId(user.getUserId());
        dto.setFirstName(user.getFirstName());
        dto.setLastName(user.getLastName());
        dto.setContactNo(user.getContactNo());
        dto.setSalary(user.getSalary());

        // Convert Role Integer back to String
        dto.setUserRole(user.getUserRole() == 1 ? "Admin" : "Staff");

        // Convert java.util.Date back to LocalDate
        if (user.getHireDate() != null) {
            LocalDate localDate = user.getHireDate();
            dto.setHireDate(localDate);
        }

        dto.setActive(user.isActive());

        // Extract Credentials
        if (user.getUserCredential() != null) {
            dto.setEmail(user.getUserCredential().getEmail());
            dto.setPassword(user.getUserCredential().getPassword());
            dto.setConfirmPassword(user.getUserCredential().getPassword());
        }

        return dto;
    }
}
